---

- hosts: localhost
  roles:
    - cleanup
    - common

    - brave
    - fish

    - vscode
    - development-tools
    - dotnet-core
    - docker
    - kubernetes

    - os-configuration
    
  vars_files: 
    - vars.yml