---

- hosts: localhost
  pre_tasks:
    - fail:
        msg: "Distribution {{ ansible_distribution }}-{{ ansible_distribution_major_version }} not supported. Supported: {{ distribution }}-{{ distribution_major_version }}"
      when:
        - ansible_distribution != "{{ distribution }}"
        - ansible_distribution_major_version != "{{ distribution_major_version }}"
  roles:
    - common
    - development-tools
    - home_dir
    
  vars_files: 
    - vars.yml