---

- name: Add kubernetes system repository
  template: 
    src: kubernetes_repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo
  become: yes

- name: Install kubernetes & kubectl
  package: 
     name: 
       - kubectl
     state: latest
  become: yes

- name: Install kubectx
  package: 
     name: 
       - kubectx
     state: latest
     enablerepo: 'cerenit/kubectx'
  become: yes

