---

- name: Add docker repository
  template: 
    src: docker_ce_repo.j2
    dest: /etc/yum.repos.d/docker-ce.repo
  become: yes

- name: Install docker
  package: 
    name: docker-ce
  become: yes

- name: Add user to docker group
  user: 
     name: "{{ansible_user}}"
     groups: docker
     append: yes
  become: yes

- name: Enable docker service at startup
  systemd:
    name: docker
    enabled: true
  become: yes

- name: Download docker-compose
  get_url: 
      url: "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-{{ansible_system}}-{{ansible_userspace_architecture}}"
      dest: /usr/local/bin/docker-compose
      owner: "{{ansible_user}}"
      mode: 0755
  become: yes